pyinstaller --onefile "publish_tasks.spec"
pyinstaller --onefile "verify_attachments.spec"
pyinstaller --onefile "verify_move_periods.spec"
pyinstaller --onefile "verify_payments.spec"
pyinstaller --onefile "tool_accountant.spec"